#!/bin/bash

set -e

#---------------------------------------------------
# Set up ENV
#---------------------------------------------------

export OS_USERNAME=""
export OS_AUTH_KEY=""
export OS_AUTH_TENANT=""
export OS_STRATEGY=""
export OS_AUTH_STRATEGY=""
export OS_AUTH_URL=""
export http_proxy=""
export https_proxy=""
export ftp_proxy=""
 
export OS_TENANT_NAME=service
export OS_USERNAME=%KEYSTONE_SERVICE_USER_NAME%
export OS_PASSWORD=%KEYSTONE_SERVICE_PASSWORD%
export OS_AUTH_URL="http://%KEYSTONE_HOST%:5000/v2.0/"

logfile=%logfile%
SWIFT_DIR=%SWIFT_DIR%
DEST=%DEST%
SERVICE_NAME=%SERVICE_NAME%
mkdir -p ${logfile%/*}
VIR_DIR=%VIR_DIR%

#---------------------------------------------------
# Use virtualenv
#---------------------------------------------------

if [[ -e $VIR_DIR ]]; then
    source $VIR_DIR/bin/activate
fi


#---------------------------------------------------
# Check keystone is running?
#---------------------------------------------------

is_running=`ps aux | grep "%SERVICE_NAME%" | grep python | grep -v grep | wc -l`


#---------------------------------------------------
# Test function for Keystone
#---------------------------------------------------



function test_service() {
    export http_proxy=""
    export https_proxy=""
    export ftp_proxy=""
    # %ADD TEST_SERVICE HERE%
}

function start_service() {
    # %ADD START_SERVICE HERE%
}

function stop_service() {
    # %ADD STOP_SERVICE HERE%
}

case "$1" in
    status)
        if [[ $is_running -gt 0 ]]; then
            echo "%SERVICE_NAME% is running"
            tail -5 $logfile
        else
            echo "swift is not running"
            cat $logfile | grep -i "error" | tail -5
        fi
        ;;
    start)
        if [[ $is_running -gt 0 ]]; then
            echo "swift is running"
        else
            start_service
            echo "swift begin to start, please wait."
            sleep 5
            cat $logfile | tail -5
        fi
        ;;
    stop)
        if [[ $is_running -gt 0 ]]; then
            echo "begin to stop swift-proxy"
            stop_service
        else
            echo "swift-proxy is stopped"
        fi
        ;;
    restart)
        if [[ $is_running -gt 0 ]]; then
            stop_service
        fi

        start_service

        echo "swift-proxy begin to start, please wait."
        sleep 5
        cat $logfile | tail -5
 
        ;;
    *)
        echo "Usage: service swift-proxy {start|stop|restart|status}"
        exit 0;;
esac

if [[ -e $VIR_DIR ]]; then
    deactivate
fi
