#!/bin/bash

set -e

#---------------------------------------------------
# Set up ENV
#---------------------------------------------------

export OS_USERNAME=""
export OS_AUTH_KEY=""
export OS_AUTH_TENANT=""
export OS_STRATEGY=""
export OS_AUTH_STRATEGY=""
export OS_AUTH_URL=""



export OS_TENANT_NAME=service
export OS_USERNAME=swift
export OS_PASSWORD=%KEYSTONE_SWIFT_SERVICE_PASSWORD%
export OS_AUTH_URL="http://%KEYSTONE_HOST%:5000/v2.0/"
logfile=%logfile%
SWIFT_DIR=%SWIFT_DIR%
DEST=%DEST%
mkdir -p /var/log/swift

#---------------------------------------------------
# Use virtualenv
#---------------------------------------------------

if [[ -e $DEST/.swift ]]; then
    source $DEST/.swift/bin/activate
fi


#---------------------------------------------------
# Check keystone is running?
#---------------------------------------------------

is_running=`ps aux | grep swift-proxy-server | grep -v grep | wc -l`


#---------------------------------------------------
# Test function for Keystone
#---------------------------------------------------



function test_service() {
    # Need to unset these proxy variables.
    export http_proxy=""
    export https_proxy=""
    export ftp_proxy=""
    swift stat
}

function start_service() {
    old_path=`pwd`
    cd $SWIFT_DIR
    nohup python ./bin/swift-proxy-server \
        /etc/swift/proxy-server.conf -v \
        > /var/log/swift/swift.log 2>&1 &
    cd $old_path
}

case "$1" in
    status)
        if [[ $is_running -gt 0 ]]; then
            echo "swift is running"
            tail -5 $logfile
        else
            echo "swift is not running"
            cat $logfile | grep -i "error" | tail -5
        fi
        ;;
    start)
        if [[ $is_running -gt 0 ]]; then
            echo "swift is running"
        else
            start_service
            echo "swift begin to start, please wait."
            sleep 5
            cat $logfile | tail -5
        fi
        ;;
    stop)
        if [[ $is_running -gt 0 ]]; then
            echo "begin to stop swift-proxy"
            nkill swift-proxy >/dev/null 2>&1 &
        else
            echo "swift-proxy is stopped"
        fi
        ;;
    restart)
        if [[ $is_running -gt 0 ]]; then
            nkill swift-proxy > /dev/null
        fi

        start_service

        echo "swift-proxy begin to start, please wait."
        sleep 5
        cat $logfile | tail -5
 
        ;;
    test)
        if [[ $is_running -gt 0 ]]; then
            test_service
        else
            echo "swift-proxy is not running"
            exit 0
        fi
        ;;
    *)
        echo "Usage: service swift-proxy {start|stop|restart|status|test}"
        exit 0;;
esac

if [[ -e $DEST/.swift ]]; then
    old_path=`pwd`
    cd $DEST/.swift/bin
    deactivate
    cd $old_path
fi
